specializer: Rename every "mit_profile" and "mit-profile" to "profile"
This anticipates the specializer becoming a separate project, not
specific to Mit.

Exception: the script "mit-profile" becomes "analyze-profile", because
that's what it does.